# Generated by Django 5.1.6 on 2025-02-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplan',
            name='activities',
            field=models.ManyToManyField(blank=True, to='track.activity'),
        ),
    ]
