# Generated by Django 5.1.6 on 2025-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_activityplan_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
