# Generated by Django 5.1.6 on 2025-02-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_activityplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
